// @ts-check
// Eén unified wiki-sidebar voor beide talen (NL = docs/, EN = docs-en/).
//
// MAP-GESTUURD: elke menu-sectie komt overeen met een map. De items binnen een
// sectie worden uit die map gelezen en geordend op `sidebar_position` (in de
// frontmatter — instelbaar via de CMS). Een nieuwe pagina in een map verschijnt
// dus automatisch in die menu-sectie, op de gekozen positie. Pagina's die in
// géén gemapte map vallen, komen onderaan onder "Overig / More".

import fs from 'node:fs';
import path from 'node:path';

const isEN = process.env.WIKI_LANG === 'en';
const t = (nl, en) => (isEN ? en : nl);
const DIR = isEN ? 'en/docs' : 'nl/docs';

const included = new Set();

/** Read sidebar_position + a display title from a doc's frontmatter. */
function meta(id) {
  let pos = 1e9;
  let title = id;
  try {
    const c = fs.readFileSync(path.join(DIR, `${id}.md`), 'utf8');
    const m = c.match(/^---\r?\n([\s\S]*?)\r?\n---/);
    if (m) {
      const p = m[1].match(/^sidebar_position:\s*(\d+)/m);
      if (p) pos = parseInt(p[1], 10);
      const tt = m[1].match(/^(?:sidebar_label|title):\s*["']?(.+?)["']?\s*$/m);
      if (tt) title = tt[1];
    }
  } catch {
    /* ignore */
  }
  return { pos, title };
}

/** Direct .md children of a subfolder, as doc-ids. */
function folderDocs(sub) {
  const full = path.join(DIR, sub);
  if (!fs.existsSync(full)) return [];
  return fs
    .readdirSync(full)
    .filter((f) => f.endsWith('.md'))
    .map((f) => `${sub}/${f.replace(/\.md$/, '')}`);
}

function sortIds(ids) {
  return [...ids].sort((a, b) => {
    const ma = meta(a);
    const mb = meta(b);
    return ma.pos - mb.pos || ma.title.localeCompare(mb.title);
  });
}

function doc(id) {
  included.add(id);
  return id;
}

/** A category whose items come from `folder`, ordered by sidebar_position. */
function section(folder, label, { extra = [], exclude = [] } = {}) {
  const ids = sortIds(folderDocs(folder).filter((id) => !exclude.includes(id)));
  ids.forEach((id) => included.add(id));
  return { type: 'category', label, items: [...ids, ...extra] };
}

const wikiSidebar = [
  doc('intro'),
  section('product', 'Product'),
  section('concepten', t('Concepten', 'Concepts')),
  section('architectuur', t('Architectuur', 'Architecture')),
  section('frontend', t('Gebruik (frontend)', 'Using the app (frontend)')),
  section('setup', t('Setup & installatie', 'Setup & installation')),
  section('integraties', t('Integraties & databronnen', 'Integrations & data sources'), {
    extra: [
      {
        type: 'category',
        label: t('Bronnen (A–Z)', 'Sources (A–Z)'),
        items: [{ type: 'autogenerated', dirName: 'integraties/bronnen' }],
      },
    ],
  }),
  section('referentie', t('Referentie', 'Reference'), {
    exclude: ['referentie/sql-interaction'],
    extra: [
      {
        type: 'category',
        label: 'SQL Interaction',
        link: { type: 'doc', id: 'referentie/sql-interaction' },
        items: sortIds(folderDocs('referentie/sql')),
      },
    ],
  }),
  doc('prijzen'),
  section('klanten', t('Klanten', 'Customers')),
  doc('faq'),
  doc('troubleshooting'),
  section('team', t('Team & processen', 'Team & processes')),
];

// Mark docs covered by special sub-sections so they don't show under "Overig".
folderDocs('integraties/bronnen').forEach((id) => included.add(id));
folderDocs('referentie/sql').forEach((id) => included.add(id));
included.add('referentie/sql-interaction');

/* ---- Any page not placed above (e.g. a new top-level page) → "Overig". ---- */
function allDocIds() {
  const out = [];
  const walk = (dir) => {
    if (!fs.existsSync(dir)) return;
    for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) walk(full);
      else if (e.name.endsWith('.md')) {
        out.push(path.relative(DIR, full).replace(/\\/g, '/').replace(/\.md$/, ''));
      }
    }
  };
  walk(DIR);
  return out;
}

try {
  const unlisted = allDocIds()
    .filter((id) => !included.has(id))
    .sort((a, b) => a.localeCompare(b));
  if (unlisted.length > 0) {
    wikiSidebar.push({
      type: 'category',
      label: t('Overig', 'More'),
      collapsed: false,
      items: unlisted.map((id) => ({ type: 'doc', id })),
    });
  }
} catch {
  /* fall back to the curated sections */
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = { wikiSidebar };

export default sidebars;
