// @ts-check
// Eén unified wiki-sidebar voor beide talen (NL = docs/, EN = docs-en/).
// Doc-ids zijn identiek in beide mappen; alleen de categorielabels schakelen op WIKI_LANG.

const isEN = process.env.WIKI_LANG === 'en';
const t = (nl, en) => (isEN ? en : nl);

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Product',
      collapsed: false,
      items: [
        'product/overzicht',
        'product/use-cases',
        'product/features',
        'product/hoe-het-werkt',
      ],
    },
    {
      type: 'category',
      label: t('Concepten', 'Concepts'),
      collapsed: false,
      items: [
        'yres-uitgelegd',
        'concepten/load-types',
        'glossary',
      ],
    },
    {
      type: 'category',
      label: t('Architectuur', 'Architecture'),
      items: [
        'architectuur',
        'referentie/azure-architectuur',
      ],
    },
    {
      type: 'category',
      label: t('Gebruik (frontend)', 'Using the app (frontend)'),
      items: [
        'frontend/dashboard',
        'frontend/admin',
        'frontend/projecten-changes',
        'frontend/data-sources',
        'frontend/load-management',
        'frontend/data-engineering',
        'frontend/account',
      ],
    },
    {
      type: 'category',
      label: t('Setup & installatie', 'Setup & installation'),
      items: [
        'setup/installatie',
        'setup/aan-de-slag',
        'setup/databron-koppelen',
        'setup/views-pipelines',
      ],
    },
    {
      type: 'category',
      label: t('Integraties & databronnen', 'Integrations & data sources'),
      items: [
        'integraties/overzicht',
        'integraties/catalogus',
        'referentie/databron-vereisten',
        {
          type: 'category',
          label: t('Bronnen (A–Z)', 'Sources (A–Z)'),
          items: [{type: 'autogenerated', dirName: 'integraties/bronnen'}],
        },
      ],
    },
    {
      type: 'category',
      label: t('Referentie', 'Reference'),
      items: [
        {
          type: 'category',
          label: 'SQL Interaction',
          link: {type: 'doc', id: 'referentie/sql-interaction'},
          items: [
            'referentie/sql/stored-procedures',
            'referentie/sql/functions',
            'referentie/sql/logs-views',
          ],
        },
        'referentie/webapp-schermen',
        'referentie/release-notes',
      ],
    },
    'prijzen',
    {
      type: 'category',
      label: t('Klanten', 'Customers'),
      items: [
        'klanten/overzicht',
        'klanten/paragon',
        'klanten/thuis',
      ],
    },
    'faq',
    'troubleshooting',
    {
      type: 'category',
      label: t('Team & processen', 'Team & processes'),
      items: [
        'team/organisatie',
        'team/klant-onboarding',
        'team/support',
        'team/sales',
      ],
    },
  ],
};

export default sidebars;
