// @ts-check
// Volledig MAP-GESTUURD en recursief: de sidebar wordt automatisch opgebouwd
// uit de mappenstructuur (NL = nl/docs/, EN = en/docs/). Elke (geneste) map
// wordt een (geneste) categorie; volgorde + labels komen uit `_category_.json`
// (gegenereerd door scripts/build-cms-config.mjs) en uit `sidebar_position` in
// de frontmatter. Een nieuwe (sub)map met pagina's verschijnt dus vanzelf in
// het menu — geen handmatige aanpassing nodig.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
